import LoggedInHeader from '@/components/LoggedInHeader';
import '@/styles/globals.css'
import { Almarai } from "next/font/google";

const almarai = Almarai({ subsets: ["arabic"] , weight:["300","400","700","800"] });

export const metadata = {
  title: "SEKOR",
  description: "Generated by SEKOR",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html dir="rtl" lang="ar">
      <body className={`bg-gray-200 font-sans font-bold text-gray-800  ${almarai.className} `}>
        <LoggedInHeader />
        {children}
      </body>
    </html>
  );
}
