import LoggedInHeader from '@/components/LoggedInHeader';
import '@/styles/globals.css'
import { Almarai } from "next/font/google";


// this made just for the production environment 
// because the in the development environment there is problem with it in nextjs 13.4+
// const almarai = Almarai({ subsets: ["arabic"] , weight:["300","400","700","800"] });
// ${almarai.className} 
export const metadata = {
  title: "SEKOR",
  description: "Generated by SEKOR",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html dir="rtl" lang="ar">
      <body className={`bg-gray-200 font-bold text-gray-800  `}>
        <LoggedInHeader />
        {children}
      </body>
    </html>
  );
}
